### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by larsbuch** [simoneb/dgml2#1]
License missing from repository. It would be nice to know how the code is allowed to be used.

**Comment by simoneb** [comment]
Good point, never thought this would be of some use for anyone. I'm not even sure the code works at all. Fixed though.

**Comment by larsbuch** [comment]
I might use it but I needed to know under which licence. I guess you need to fill out the "year" & "copyright holders" in the start of the licence

**Comment by simoneb** [comment]
ok
